-- MySQL Script generated by MySQL Workbench
-- Fri May 20 11:05:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema introDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema introDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `introDB` DEFAULT CHARACTER SET utf8 ;
USE `introDB` ;

-- -----------------------------------------------------
-- Table `introDB`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introDB`.`marcas` (
  `idMarca` TINYINT(255) NOT NULL AUTO_INCREMENT,
  `mkNombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `introDB`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introDB`.`categorias` (
  `idCategoria` TINYINT(255) NOT NULL AUTO_INCREMENT,
  `catNombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `introDB`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introDB`.`productos` (
  `idProducto` MEDIUMINT NOT NULL,
  `prdNombre` VARCHAR(45) NOT NULL,
  `prdPrecio` FLOAT(8,2) NOT NULL,
  `idMarca` TINYINT(255) NOT NULL,
  `idCategoria` TINYINT(255) NOT NULL,
  `prdDescripcion` VARCHAR(500) NOT NULL,
  `prdImagen` VARCHAR(45) NOT NULL,
  `prdActivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_productos_marcas_idx` (`idMarca` ASC) VISIBLE,
  INDEX `fk_productos_categorias1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_productos_marcas`
    FOREIGN KEY (`idMarca`)
    REFERENCES `introDB`.`marcas` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `introDB`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
